spring:
  application:
    name: Test

  # Configuration de la source de données MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/CinemaLibreDeDroit
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration de JPA (Java Persistence API)
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true